apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app.kubernetes.io/name: flask
spec:
  containers:
    - name: app
      image: docker.io/shaiperets/perimeter81:latest
      env:
      - name: PORT
        value: "5000"
      - name: ENVIRONMENT
        value: "production"
      ports:
        - containerPort: 5000
          name: http
